# Generated by Django 6.0.4 on 2026-04-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('command', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='commands/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labels', models.ManyToManyField(related_name='commands', to='commands.label')),
            ],
        ),
    ]
