# Generated by Django 6.0.4 on 2026-04-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='image',
        ),
    ]
